# Generated by Django 4.1.1 on 2023-09-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='model_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
