# Generated by Django 4.1.1 on 2023-09-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_conversation_conversation_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_msg',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
