# Generated by Django 4.1.1 on 2023-10-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_chatlog_chatlog_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='chatlog_id_str',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='conversation',
            name='conversation_id_str',
            field=models.CharField(default='', max_length=100),
        ),
    ]
