# Generated by Django 4.1.1 on 2023-09-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chatlog',
        ),
    ]
