# Generated by Django 4.1.1 on 2022-10-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('utorid', models.CharField(max_length=10)),
                ('user_role', models.CharField(max_length=2)),
            ],
        ),
    ]
