# Generated by Django 4.1.1 on 2023-02-01 05:14

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=100)),
                ('chatlog_id', models.CharField(max_length=100)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('is_user', models.BooleanField()),
                ('chatlog', models.TextField(max_length=3000)),
                ('delta', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=1)),
                ('report', models.BooleanField()),
                ('comfortability_rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=10)),
                ('course_code', models.CharField(max_length=9)),
                ('course_name', models.TextField(max_length=1000)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('feedback_msg', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='GPTModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=100)),
                ('model_name', models.TextField(max_length=100)),
                ('course_id', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('model', models.TextField(max_length=40)),
                ('prompt', models.TextField(max_length=2000)),
                ('suffix', models.TextField(blank=True, max_length=100, null=True)),
                ('max_tokens', models.IntegerField(default=16)),
                ('temperature', models.FloatField(default=1)),
                ('top_p', models.FloatField(default=1)),
                ('n', models.IntegerField(default=1)),
                ('stream', models.BooleanField(default=False)),
                ('logprobs', models.IntegerField(default=None)),
                ('presence_penalty', models.FloatField(default=0)),
                ('frequency_penalty', models.FloatField(default=0)),
                ('best_of', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('utorid', models.CharField(max_length=10)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=1)),
                ('msg', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('utorid', models.CharField(max_length=10)),
                ('user_role', models.CharField(max_length=2)),
            ],
        ),
    ]
