# Generated by Django 4.1.1 on 2022-10-22 21:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=10)),
                ('course_code', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=20)),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Unsatisfactory'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('feedback_msg', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('utorid', models.CharField(max_length=10)),
                ('user_role', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_msg', models.TextField(max_length=3000)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=20)),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.course')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.course'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.user'),
        ),
        migrations.CreateModel(
            name='Chatlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatlog_id', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('is_user', models.BooleanField()),
                ('chatlog', models.TextField(max_length=3000)),
                ('conversation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.conversation')),
            ],
        ),
    ]
