# Generated by Django 4.1.1 on 2023-09-28 16:12

import datetime
from django.db import migrations, models
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_id', models.CharField(max_length=100)),
                ('assessment_question_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('response_choice', models.TextField()),
                ('correct', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('assessment_name', models.TextField()),
                ('status', models.CharField(default='A', max_length=1)),
                ('question_bank', djongo.models.fields.JSONField(blank=True, default=[], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_question_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.TextField(choices=[('Tech', 'Tech')])),
                ('language', models.TextField(choices=[('Python', 'Python'), ('Java', 'Java'), ('SQL', 'SQL')])),
                ('question', models.TextField()),
                ('choices', djongo.models.fields.JSONField()),
                ('correct_answer', models.TextField()),
                ('correct_answer_flavor_text', models.TextField()),
            ],
        ),
    ]
