# Generated by Django 4.1.1 on 2023-09-08 08:52

from django.db import migrations, models
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('semester', models.CharField(max_length=10)),
                ('course_code', models.CharField(max_length=9)),
                ('course_name', models.TextField(max_length=1000)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('students', djongo.models.fields.JSONField(blank=True, default=[], null=True)),
            ],
        ),
    ]
