# Generated by Django 4.1.1 on 2023-09-08 13:30

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='admins',
            field=djongo.models.fields.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=djongo.models.fields.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='researchers',
            field=djongo.models.fields.JSONField(blank=True, default=[], null=True),
        ),
    ]
