# Generated by Django 4.1.1 on 2023-09-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_admins_course_instructors_course_researchers'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_id'], name='course_id_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_name'], name='course_name'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['semester'], name='semester'),
        ),
    ]
