# Generated by Django 4.1.1 on 2023-10-21 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_course_id_idx_course_course_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_id', models.CharField(default=uuid.UUID('58962d26-0781-46bd-b1e0-44d5187382c4'), editable=False, max_length=50, unique=True)),
                ('deployment_name', models.TextField(max_length=1000)),
                ('course_id', models.CharField(max_length=50)),
                ('status', models.CharField(default='A', max_length=1)),
            ],
        ),
    ]
