# Generated by Django 4.1.1 on 2023-10-24 18:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_coursedeployment_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedeployment',
            name='deployment_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True),
        ),
    ]
