# Generated by Django 4.1.1 on 2023-10-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_coursedeployment_deployment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='coursedeployment',
            name='deployment_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
