# Generated by Django 4.1.1 on 2023-11-06 19:08

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedeployment',
            name='assessment_ids',
            field=djongo.models.fields.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AddField(
            model_name='coursedeployment',
            name='survey_ids',
            field=djongo.models.fields.JSONField(blank=True, default=[], null=True),
        ),
    ]
