# Generated by Django 4.1.1 on 2023-09-14 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPTModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('model_name', models.TextField(max_length=100)),
                ('course_id', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('model', models.TextField(max_length=40)),
                ('prompt', models.TextField(max_length=2000)),
                ('suffix', models.TextField(blank=True, max_length=100, null=True)),
                ('max_tokens', models.IntegerField(default=16)),
                ('temperature', models.FloatField(default=1)),
                ('top_p', models.FloatField(default=1)),
                ('n', models.IntegerField(default=1)),
                ('stream', models.BooleanField(default=False)),
                ('logprobs', models.IntegerField(default=None)),
                ('presence_penalty', models.FloatField(default=0)),
                ('frequency_penalty', models.FloatField(default=0)),
                ('best_of', models.IntegerField(default=1)),
            ],
        ),
    ]
