# Generated by Django 4.1.1 on 2023-09-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_gptmodel_model_description'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gptmodel',
            index=models.Index(fields=['model_id'], name='model_id_idx'),
        ),
        migrations.AddIndex(
            model_name='gptmodel',
            index=models.Index(fields=['model_name'], name='model_name'),
        ),
        migrations.AddIndex(
            model_name='gptmodel',
            index=models.Index(fields=['course_id'], name='course_id'),
        ),
    ]
