# Generated by Django 4.1.1 on 2023-09-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_gptmodel_model_id_idx_gptmodel_model_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptmodel',
            name='prompt',
            field=models.TextField(max_length=10000),
        ),
    ]
