# Generated by Django 4.1.1 on 2023-10-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_alter_gptmodel_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptmodel',
            name='deployment_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
