# Generated by Django 4.1.1 on 2023-10-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_gptmodel_deployment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptmodel',
            name='model_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
