# Generated by Django 4.1.1 on 2023-11-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_alter_gptmodel_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptmodel',
            name='model_type',
            field=models.CharField(default='gpt', max_length=100),
        ),
    ]
