# Generated by Django 4.1.1 on 2023-11-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_gptmodel_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptmodel',
            name='default_message',
            field=models.TextField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='gptmodel',
            name='model_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
