# Generated by Django 4.1.1 on 2023-11-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_gptmodel_default_message_alter_gptmodel_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptmodel',
            name='default_conversation_name',
            field=models.TextField(default='', max_length=100000),
        ),
    ]
