# Generated by Django 4.1.1 on 2023-09-08 08:52

from django.db import migrations, models
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('utorid', models.CharField(max_length=10)),
                ('user_role', models.CharField(max_length=2)),
                ('courses', djongo.models.fields.JSONField(blank=True, default=[], null=True)),
            ],
        ),
    ]
