# Generated by Django 4.1.1 on 2023-09-27 17:29

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_id_idx_user_utorid_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='model_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='new_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='post_survey',
            field=djongo.models.fields.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pre_survey',
            field=djongo.models.fields.JSONField(blank=True, default=[], null=True),
        ),
    ]
