# Generated by Django 4.1.1 on 2023-09-28 16:12

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_model_id_user_new_user_user_post_survey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assessment_responses',
            field=djongo.models.fields.JSONField(blank=True, default=[], null=True),
        ),
    ]
