# Generated by Django 4.1.1 on 2023-11-05 00:30

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=djongo.models.fields.JSONField(blank=True, default=[], null=True),
        ),
    ]
